language: ruby
rvm:
  - 2.2.9
services:
  - postgresql
install:
  - bundle install --jobs=3 --retry=3
before_script:
  - psql -c 'create database "footprints-public_test";' -U postgres
script:
  - RAILS_ENV=test bundle exec rake db:test:prepare
  - bundle exec rake
